source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2" # Example Ruby version, adjust as needed for typical Rails 7

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.8"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use Puma as the app server
gem "puma", "~> 5.0"

# Build JSON APIs with Jbuilder
gem "jbuilder", "~> 2.0"
# Use Redis caching within Rails
gem "redis-rails"

# Hotwire!
gem "hotwire-rails"
# Use stimulus-rails with importmap by default.
gem "stimulus-rails"
# Use turbo-rails with importmap by default.
gem "turbo-rails"


# Tailwind CSS
gem "tailwindcss-rails"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages
  gem "web-console"
  # Add speed badges to page loads in browser
  gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps by caching results
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem "capybara"
  gem "selenium-webdriver"
  # Easy installation and use of web drivers for system tests
  gem "webdrivers"
  # RSpec for testing
  gem "rspec-rails"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw ]

# Our primary Redis client
gem "redis", "~> 5.0"
