# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS via Homebrew:
#   brew install postgresql
# On macOS via MacPorts:
#   sudo port install postgresql96
# On Windows:
#   gem install pg -- --with-pg-config=/path/to/postgresql/bin/pg_config
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ultradex_development
  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # If undefined, the role used is "postgres"
  # username: ultradex
  # password:
  # host: localhost
  # port: 5432

test:
  <<: *default
  database: ultradex_test

production:
  <<: *default
  database: ultradex_production
  username: ultradex
  password: <%= ENV["ULTRADEX_DATABASE_PASSWORD"] %>
