name: CI

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose and Build services
        working-directory: ./ultradex
        run: |
          docker compose build
          docker compose up -d

      - name: Prepare test database
        working-directory: ./ultradex
        run: |
          echo "Waiting for services to be healthy..."
          # Add a short delay or a more sophisticated wait for services like PostgreSQL
          # For now, a simple sleep. This might need refinement.
          sleep 20
          docker compose exec -T app bin/rails db:setup

      - name: Run RSpec tests
        working-directory: ./ultradex
        run: |
          docker compose exec -T app bundle exec rspec

      - name: Stop Docker services
        if: always() # Ensure services are stopped even if previous steps fail
        working-directory: ./ultradex
        run: |
          docker compose down

      - name: Capture logs on failure
        if: failure()
        working-directory: ./ultradex
        run: |
          mkdir -p ../../build_failures
          # Ensure the log command also uses the correct relative path for output
          docker compose logs > ../../build_failures/logs_${{ github.run_id }}_$(date +%s).txt

      - name: Commit failure logs
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "CI: Commit failure logs for run ${{ github.run_id }}"
          branch: ${{ github.head_ref || github.ref_name }}
          file_pattern: build_failures/*
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
