name: CI

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose and Build services
        working-directory: ./ultradex
        run: |
          set -e # Ensure script exits on first error
          echo "Running docker compose build..."
          docker compose -f docker-compose.yml build > $GITHUB_WORKSPACE/docker_build_output.log 2>&1
          BUILD_EXIT_CODE=$?
          if [ $BUILD_EXIT_CODE -ne 0 ]; then
            echo "Docker compose build failed with exit code $BUILD_EXIT_CODE. Full log:"
            cat $GITHUB_WORKSPACE/docker_build_output.log
            exit $BUILD_EXIT_CODE
          fi
          echo "Docker compose build successful."

          echo "Running docker compose up -d..."
           docker compose -f docker-compose.yml up -d > $GITHUB_WORKSPACE/docker_up_output.log 2>&1
          UP_EXIT_CODE=$?
          if [ $UP_EXIT_CODE -ne 0 ]; then
            echo "Docker compose up -d failed with exit code $UP_EXIT_CODE. Full log:"
            cat $GITHUB_WORKSPACE/docker_up_output.log
            # Also output build log for context if up fails, as it might be related
            echo "--- Docker Build Log (for context as 'up' failed) ---"
            cat $GITHUB_WORKSPACE/docker_build_output.log
            exit $UP_EXIT_CODE
          fi
          echo "Docker compose up -d successful."

      - name: Debug Container Environment
        working-directory: ./ultradex
        run: |
          docker compose -f docker-compose.yml exec -T app sh -c '
          echo "--- Debugging Container Environment (non-blocking) ---";
          echo "=== Phase 1: Running as current user (\$(whoami)) ===";
          pwd;
          echo "Listing /usr/src/app:";
          ls -la /usr/src/app || true;
          echo "Stat /usr/src/app/config:";
          stat /usr/src/app/config || echo "DEBUG ALERT: stat /usr/src/app/config failed";
          echo "Stat /usr/src/app/config/environment.rb:";
          stat /usr/src/app/config/environment.rb || echo "DEBUG ALERT: stat /usr/src/app/config/environment.rb failed";
          echo "Stat /usr/src/app/spec/rails_helper.rb:";
          stat /usr/src/app/spec/rails_helper.rb || echo "DEBUG ALERT: stat /usr/src/app/spec/rails_helper.rb failed";
          echo "Mount info for /usr/src/app:";
          df -h /usr/src/app || true;
          mount | grep /usr/src/app || echo "DEBUG INFO: /usr/src/app not found in mount output";
          echo "";
          echo "=== Phase 2: Switching to appuser (attempt) ===";
          su appuser -c "
            echo \"--- Running as appuser (\$(whoami)) ---\";
            echo \"Initial PWD for appuser: \$(pwd)\";
            echo \"Attempting: cd /usr/src/app\";
            cd /usr/src/app || { echo \"DEBUG ALERT: \$(whoami) FAILED to cd to /usr/src/app\"; exit 0; }; # exit 0 to not fail parent
            echo \"PWD after cd: \$(pwd)\";
            echo \\\"\\\";
            echo \"--- File & Directory Checks (as \$(whoami) in \$(pwd)) ---\";
            echo \"Listing current directory (\$(pwd)) with ls -la .:\";
            ls -la . || true;
            echo \"Listing ./config (ls -la ./config):\";
            ls -la ./config || echo \"DEBUG ALERT: ./config not found or not listable by \$(whoami)\";
            echo \"Listing ./spec (ls -la ./spec):\";
            ls -la ./spec || echo \"DEBUG ALERT: ./spec not found or not listable by \$(whoami)\";
            echo \\\"\\\";
            echo \"Checking ./config/environment.rb with ls -laL ./config/environment.rb (dereference symlinks):\";
            ls -laL ./config/environment.rb || echo \"DEBUG ALERT: ./config/environment.rb not found (ls -laL) by \$(whoami)\";
            echo \"Stat ./config/environment.rb:\";
            stat ./config/environment.rb || echo \"DEBUG ALERT: stat ./config/environment.rb failed for \$(whoami)\";
            echo \"Head of ./config/environment.rb (first 5 lines):\";
            head -n 5 ./config/environment.rb || echo \"DEBUG ALERT: head ./config/environment.rb failed for \$(whoami)\";
            echo \\\"\\\";
            echo \"Checking ./spec/rails_helper.rb with ls -laL ./spec/rails_helper.rb:\";
            ls -laL ./spec/rails_helper.rb || echo \"DEBUG ALERT: ./spec/rails_helper.rb not found (ls -laL) by \$(whoami)\";
            echo \"Stat ./spec/rails_helper.rb:\";
            stat ./spec/rails_helper.rb || echo \"DEBUG ALERT: stat ./spec/rails_helper.rb failed for \$(whoami)\";
            echo \"Head of ./spec/rails_helper.rb (first 5 lines):\";
            head -n 5 ./spec/rails_helper.rb || echo \"DEBUG ALERT: head ./spec/rails_helper.rb failed for \$(whoami)\";
            echo \"Grep for require_relative in ./spec/rails_helper.rb:\";
            grep '\''require_relative'\'' ./spec/rails_helper.rb || echo \"DEBUG ALERT: require_relative not found in spec/rails_helper.rb by \$(whoami)\";
            echo \\\"\\\";
            echo \"--- Environment Checks (as \$(whoami) after attempting to source RVM) ---\";
            echo \"Sourcing RVM (/home/appuser/.rvm/scripts/rvm)...\";
            if [ -f /home/appuser/.rvm/scripts/rvm ]; then
              chmod +x /home/appuser/.rvm/scripts/rvm;
              source /home/appuser/.rvm/scripts/rvm || echo \"DEBUG ALERT: Failed to source RVM for \$(whoami)\";
            else
              echo \"DEBUG ALERT: RVM script /home/appuser/.rvm/scripts/rvm not found!\";
            fi;
            echo \"RVM Info (env | grep RVM):\";
            env | grep RVM || echo \"DEBUG INFO: RVM env vars not found\";
            echo \"Ruby version (ruby -v):\";
            ruby -v || echo \"DEBUG ALERT: ruby -v failed for \$(whoami)\";
            echo \"Bundler version (bundle -v):\";
            bundle -v || echo \"DEBUG ALERT: bundle -v failed for \$(whoami)\";
            echo \"GEM_HOME: \$GEM_HOME\";
            echo \"GEM_PATH: \$GEM_PATH\";
            echo \"Ruby Load Path (\\\$LOAD_PATH) - joined by newlines:\";
            ruby -e '\''puts \$LOAD_PATH.join(\"\\n\")'\'' || echo \"DEBUG ALERT: Failed to get Ruby \\\$LOAD_PATH for \$(whoami)\";
            echo \"Bundle check:\";
            bundle check || echo \"DEBUG ALERT: bundle check failed for \$(whoami)\";
            echo \\\"\\\";
            echo \"--- Path Resolution Test (as \$(whoami) from /usr/src/app/spec) ---\";
            echo \"Attempting to resolve path: Dir.chdir(\\\"/usr/src/app/spec\\\"); puts File.expand_path(\\\"../config/environment.rb\\\")\";
            ruby -e '\''Dir.chdir(\"/usr/src/app/spec\") do; puts File.expand_path(\"../config/environment.rb\"); end'\'' || echo \"DEBUG ALERT: Ruby test for resolving path failed for \$(whoami)\";
            echo \"--- End of appuser debug ---\";
          " || echo "DEBUG: su appuser -c command failed but continuing main script..."
          '

      - name: Run RSpec tests
        working-directory: ./ultradex
        run: |
          docker compose -f docker-compose.yml exec -T --user root app sh -c "cd /usr/src/app && chmod 777 Gemfile.lock || true; runuser -u appuser -- bash -c 'source /home/appuser/.rvm/scripts/rvm && cd /usr/src/app && bundle exec rspec'"

      - name: Output Failure Logs
        if: failure()
        working-directory: ./ultradex # pwd is $GITHUB_WORKSPACE/ultradex
        run: |
          BUILD_LOG_FILE="$GITHUB_WORKSPACE/docker_build_output.log"
          UP_LOG_FILE="$GITHUB_WORKSPACE/docker_up_output.log"
          PROCESSED_BUILD_OR_UP_ERROR=false

          # Intentionally minimal echos now, only outputting found errors or final status.

          if [ -f "$BUILD_LOG_FILE" ]; then
            # Grep for critical errors, show only matching lines.
            # Added 'npm: not found' directly based on observed failure.
            if grep -E -i 'ERROR|failed to build|Step [0-9]+/[0-9]+ failed|failed to fetch|npm: not found|Could not resolve|unable to access' "$BUILD_LOG_FILE"; then
              PROCESSED_BUILD_OR_UP_ERROR=true
              echo "--- Relevant lines from Docker build log above ---"
            else
              # If specific grep fails, but file exists, show last N lines as a less specific fallback.
              echo "No specific critical error markers found in Docker build log via grep. Displaying last 20 lines as fallback:"
              tail -n 20 "$BUILD_LOG_FILE"
              PROCESSED_BUILD_OR_UP_ERROR=true # Still consider it processed.
            fi
          fi

          if [ "$PROCESSED_BUILD_OR_UP_ERROR" = false ]; then
            if [ -f "$UP_LOG_FILE" ]; then
              if grep -E -i 'ERROR|Cannot start service|failed| unhealthy|exited with code' "$UP_LOG_FILE"; then
                PROCESSED_BUILD_OR_UP_ERROR=true
                echo "--- Relevant lines from Docker up log above ---"
              else
                echo "No specific critical error markers found in Docker up log via grep. Displaying last 20 lines as fallback:"
                tail -n 20 "$UP_LOG_FILE"
                PROCESSED_BUILD_OR_UP_ERROR=true
              fi
            fi
          fi

          if [ "$PROCESSED_BUILD_OR_UP_ERROR" = false ]; then
            echo "No critical errors found in build/up logs, or logs not found. Checking application service ('app') logs..."
            if [ -n "$(docker compose -f docker-compose.yml ps -q app)" ] || docker compose -f docker-compose.yml ps app | grep -iq 'exited'; then
              # RSpec logs benefit from some context.
              docker compose -f docker-compose.yml logs app | grep -E -A 30 'Failures:|Failure/Error:|Failed examples:' \
              || (echo "No RSpec failure markers found in 'app' service logs. Dumping last 50 lines of 'app' service as fallback." && docker compose -f docker-compose.yml logs app | tail -n 50)
            else
              echo "The 'app' service does not appear to have been active. No application logs to display."
            fi
          fi

      - name: Stop Docker services
        if: always() # Ensure services are stopped even if previous steps fail
        working-directory: ./ultradex
        run: |
          docker compose -f docker-compose.yml down
